#!/usr/bin/env node
/**
 * Copies the version out of package.json into the places that cannot read it.
 *
 * package.json is the single source of truth. Three other files need the same number and
 * none of them can import it: the Angular bundle (a JSON import would need resolveJsonModule
 * and would pull the whole manifest into the bundle), Gradle (different language, different
 * build), and the CI stamp. Generating them from one place is the only way they stay equal;
 * hand-editing four files is how an app ends up reporting three different versions.
 *
 * Run by `npm run prebuild`, so an ordinary `ng build` cannot produce a mismatched bundle,
 * and by CI before it stamps the APK.
 *
 * Android needs two values and they are not interchangeable. versionName is the human string
 * ("1.2.3"). versionCode is an integer Android compares to decide what counts as an upgrade,
 * so it MUST increase monotonically — encoding the three parts as major*10000 + minor*100 +
 * patch keeps it ordered and derivable, with room for 99 minors and 99 patches.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = pkg.version;

const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
if (!m) {
  console.error(`package.json version "${version}" is not MAJOR.MINOR.PATCH`);
  process.exit(1);
}
const [, major, minor, patch] = m.map(Number);
if (minor > 99 || patch > 99) {
  // Past 99 the arithmetic stops being monotonic: 1.99.0 and 2.0.0 would collide.
  console.error(`minor and patch must each stay under 100 (got ${version})`);
  process.exit(1);
}
const versionCode = major * 10000 + minor * 100 + patch;

// ---------------------------------------------------------------- the Angular bundle
writeFileSync(join(root, 'src/app/version.ts'),
`// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand —
// \`npm run sync-version\` (and every build) rewrites it.
export const APP_VERSION = '${version}';
export const APP_VERSION_CODE = ${versionCode};
`);

// ---------------------------------------------------------------- Gradle
const gradle = join(root, 'android/app/build.gradle');
if (existsSync(gradle)) {
  const before = readFileSync(gradle, 'utf8');
  const after = before
    .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
    .replace(/versionName\s+"[^"]*"/, `versionName "${version}"`);
  if (after !== before) writeFileSync(gradle, after);
}

// ---------------------------------------------------------------- CI, on request
// `--print-code` lets a workflow read the derived integer without reimplementing the rule.
if (process.argv.includes('--print-code')) console.log(versionCode);
else console.log(`version ${version} (versionCode ${versionCode})`);
