import { ConceptTopic } from './models';

/**
 * Concept questions, not algorithm problems — no brute-force/optimized split applies here,
 * just a plain-English explanation of the idea. See prep-dsa-data.ts for the DSA format.
 */
export const CS_TOPICS: ConceptTopic[] = [
  {
    name: 'Operating Systems',
    items: [
      { name: 'Process vs Thread', explanation: 'A process is an independent running program with its own memory space; a thread is a unit of execution inside a process that shares that memory with other threads in the same process. Threads are cheaper to create and switch between, but sharing memory means they can step on each other\'s data without careful synchronization.' },
      { name: 'Deadlock — conditions & prevention', explanation: 'A deadlock needs four conditions at once: mutual exclusion (resources can\'t be shared), hold-and-wait (a process holds one resource while waiting for another), no preemption (resources can\'t be forcibly taken), and circular wait (a cycle of processes each waiting on the next). Breaking any one of the four prevents deadlock — the most common approach is requiring processes to request all their resources up front, or always requesting resources in a fixed global order.' },
      { name: 'Paging vs Segmentation', explanation: 'Paging splits memory into fixed-size blocks (pages), which avoids external fragmentation but can waste space inside a page. Segmentation splits memory into variable-size logical units (like "code" or "stack"), which matches how programs actually think about memory but can fragment external free space. Most modern systems use paging, sometimes layered under a segmentation-like view.' },
      { name: 'Virtual Memory', explanation: 'Virtual memory gives each process the illusion of a large, private, contiguous address space, while the OS actually maps pieces of it to physical RAM (or disk) behind the scenes via a page table. This lets programs run without needing to fit entirely in RAM, and isolates processes from directly seeing or corrupting each other\'s memory.' },
      { name: 'CPU Scheduling Algorithms', explanation: 'Round Robin gives every process a fixed time slice in rotation, which is fair but can add overhead from frequent context switches. Shortest Job First runs whichever process needs the least CPU time next, minimizing average wait time but risking starving long jobs. Priority scheduling runs higher-priority processes first, which needs a mechanism (aging) to prevent low-priority processes from starving indefinitely.' },
      { name: 'Semaphore vs Mutex', explanation: 'A mutex is a lock meant to be held and released by the same thread, protecting a single resource from concurrent access. A semaphore is a counter that can allow a fixed number of threads through at once and can be signaled by a different thread than the one that waited — useful for producer/consumer patterns, not just simple mutual exclusion.' },
      { name: 'Context Switching', explanation: 'A context switch saves the current process/thread\'s CPU state (registers, program counter, etc.) so it can resume later, then loads another\'s saved state so it can run. It\'s necessary for multitasking, but it\'s pure overhead — no useful work happens during the switch itself, which is why excessive switching hurts performance.' },
      { name: 'Thrashing', explanation: 'Thrashing happens when a system spends more time swapping pages in and out of memory than actually executing code, usually because too many processes are competing for too little RAM. The fix is usually reducing the number of concurrently running processes (or adding RAM) rather than trying to make the swapping itself faster.' },
    ],
  },
  {
    name: 'DBMS',
    items: [
      { name: 'ACID Properties', explanation: 'Atomicity means a transaction either fully completes or fully rolls back, never partially. Consistency means a transaction moves the database from one valid state to another, respecting all constraints. Isolation means concurrent transactions don\'t see each other\'s incomplete work. Durability means once committed, a transaction survives a crash. Together they\'re what make transactions safe to reason about.' },
      { name: 'Normalization (1NF → BCNF)', explanation: 'Normalization is the process of restructuring tables to reduce redundant data and avoid update anomalies. 1NF requires atomic values in every column (no repeating groups). 2NF removes partial dependencies on a composite key. 3NF removes transitive dependencies (a non-key column depending on another non-key column). BCNF tightens 3NF further to handle some edge cases with overlapping candidate keys.' },
      { name: 'Indexing — B-Tree vs B+Tree', explanation: 'Both are balanced tree structures that let a database find rows without scanning the whole table. A B-Tree stores actual data at internal nodes as well as leaves. A B+Tree only stores data at the leaves, with internal nodes purely for navigation — and leaves are typically linked together, making range queries (like "between X and Y") much faster, which is why B+Trees are the more common choice for database indexes.' },
      { name: 'Types of Joins', explanation: 'An inner join returns only rows that match in both tables. A left (or right) outer join returns all rows from one table plus matching rows from the other, filling in nulls where there\'s no match. A full outer join returns all rows from both tables, matched where possible. A cross join returns every combination of rows from both tables (no matching condition at all).' },
      { name: 'Transactions & Isolation Levels', explanation: 'Isolation levels trade consistency for performance. Read Uncommitted allows seeing another transaction\'s uncommitted changes (dirty reads). Read Committed only sees committed data but can see different data on repeated reads within the same transaction. Repeatable Read guarantees the same read returns the same data throughout a transaction. Serializable is the strictest, behaving as if transactions ran one at a time.' },
      { name: 'CAP Theorem', explanation: 'In a distributed system, you can\'t simultaneously guarantee Consistency (every read sees the latest write), Availability (every request gets a response), and Partition tolerance (the system keeps working despite network splits) — you have to give up one when a partition actually happens. Since network partitions are unavoidable in practice, the real choice is usually between consistency and availability during a partition.' },
      { name: 'SQL vs NoSQL', explanation: 'SQL databases enforce a fixed schema and strong relational structure, which is great for data with clear relationships and strict consistency needs. NoSQL databases (document, key-value, column, graph) trade some of that structure for flexibility and horizontal scalability, which suits large-scale or rapidly-changing data models better than rigid schemas do.' },
      { name: 'Sharding vs Replication', explanation: 'Sharding splits a dataset across multiple machines, each holding a different subset of the data — this scales write and storage capacity, but makes cross-shard queries harder. Replication copies the same data across multiple machines, which scales read capacity and improves availability, but doesn\'t help you store more data than a single machine can hold.' },
    ],
  },
  {
    name: 'Computer Networks',
    items: [
      { name: 'OSI Model vs TCP/IP Model', explanation: 'The OSI model is a 7-layer conceptual framework (Physical, Data Link, Network, Transport, Session, Presentation, Application) mostly used for teaching and reasoning about networking. The TCP/IP model is the 4-layer model (Link, Internet, Transport, Application) that actually describes how the real internet is built — it\'s less precise but is what protocols like IP, TCP, and HTTP actually map onto.' },
      { name: 'TCP vs UDP', explanation: 'TCP is connection-oriented, guarantees delivery and ordering, and handles retransmission and congestion control — at the cost of extra overhead and latency. UDP is connectionless and makes no delivery guarantees, but is faster and lighter, which is why it\'s used for things like video streaming or gaming where a dropped packet is less costly than the delay of waiting for a retransmission.' },
      { name: 'HTTP vs HTTPS', explanation: 'HTTPS is HTTP layered on top of TLS encryption. The data is functionally the same, but HTTPS encrypts it in transit, preventing eavesdropping or tampering by anyone sitting on the network path, and also verifies the server\'s identity via a certificate.' },
      { name: 'DNS Resolution Process', explanation: 'A DNS lookup walks down a hierarchy: your resolver asks a root server which server handles the top-level domain (like .com), then asks that TLD server which server handles the specific domain, then asks that authoritative server for the actual IP address — with caching at every level so most lookups skip straight to a cached answer instead of walking the full chain.' },
      { name: 'Load Balancing Basics', explanation: 'A load balancer sits in front of multiple servers and distributes incoming requests among them, so no single server gets overwhelmed. Strategies include round robin (rotate through servers evenly), least connections (send to whichever server currently has the fewest active requests), and consistent hashing (route the same kind of request to the same server, useful when server-side caching matters).' },
      { name: 'REST vs GraphQL', explanation: 'REST exposes fixed endpoints that each return a fixed shape of data, which is simple but can mean over-fetching (getting fields you don\'t need) or under-fetching (needing multiple round trips). GraphQL exposes a single endpoint where the client specifies exactly which fields it wants, avoiding both problems — at the cost of more complexity on the server to support arbitrary queries efficiently.' },
      { name: 'WebSockets vs HTTP Polling', explanation: 'HTTP polling means the client repeatedly asks the server "anything new?" on an interval, which wastes requests when nothing has changed and adds latency when something has. A WebSocket opens a single persistent connection that either side can push messages over at any time, which is far more efficient for real-time updates like chat or live notifications.' },
      { name: 'CDN — how it works', explanation: 'A Content Delivery Network caches copies of static content (images, scripts, videos) on servers spread across many geographic locations, so a user\'s request is served from a nearby edge server instead of traveling all the way to the origin server — cutting latency and reducing load on the origin.' },
    ],
  },
  {
    name: 'OOP',
    items: [
      { name: 'Four Pillars: Encapsulation, Abstraction, Inheritance, Polymorphism', explanation: 'Encapsulation bundles data with the methods that operate on it and restricts direct access to internal state. Abstraction exposes only what\'s necessary and hides implementation detail behind a simpler interface. Inheritance lets a class reuse and extend another class\'s behavior. Polymorphism lets different classes be used interchangeably through a shared interface, with each providing its own specific behavior.' },
      { name: 'SOLID Principles', explanation: 'Single Responsibility: a class should have one reason to change. Open/Closed: code should be open for extension but closed for modification. Liskov Substitution: subtypes must be usable anywhere their base type is expected without breaking behavior. Interface Segregation: prefer many small, specific interfaces over one large general one. Dependency Inversion: depend on abstractions, not concrete implementations.' },
      { name: 'Interface vs Abstract Class', explanation: 'An interface declares a contract (what methods must exist) with no implementation of its own, and a class can implement multiple interfaces. An abstract class can provide partial implementation alongside abstract methods that subclasses must fill in, but most languages only allow inheriting from one abstract class. Use an interface for "can do this," an abstract class for "is a kind of this, with shared behavior."' },
      { name: 'Method Overloading vs Overriding', explanation: 'Overloading means defining multiple methods with the same name but different parameters within the same class — resolved at compile time based on the arguments passed. Overriding means a subclass provides its own implementation of a method already defined in its parent class — resolved at runtime based on the actual object\'s type.' },
      { name: 'Composition vs Inheritance', explanation: 'Inheritance models an "is-a" relationship (a Dog is an Animal) and can create tight coupling between classes that\'s hard to change later. Composition models a "has-a" relationship (a Car has an Engine) by building objects out of other objects, which tends to be more flexible since components can be swapped out independently — a common guideline is to favor composition over inheritance when either would work.' },
      { name: 'Common Design Patterns', explanation: 'Singleton ensures a class has only one instance, globally accessible — useful for shared resources like a config object, though overuse can hide dependencies. Factory delegates object creation to a separate method or class, decoupling code from concrete classes it needs to instantiate. Observer lets objects subscribe to and get notified of another object\'s state changes, which is the basis of most event-driven and pub/sub systems.' },
      { name: 'Static vs Dynamic Binding', explanation: 'Static binding resolves which method to call at compile time, based on the declared type of a reference — this is how overloaded methods are resolved. Dynamic binding resolves which method to call at runtime, based on the actual object\'s type — this is how overridden methods achieve polymorphism.' },
      { name: 'Constructor vs Destructor', explanation: 'A constructor runs when an object is created, typically to initialize its state. A destructor (in languages that have them, like C++) runs when an object is destroyed, typically to release resources it was holding. Languages with garbage collection, like Java or JavaScript, usually don\'t expose deterministic destructors — cleanup instead relies on patterns like try-with-resources or explicit dispose methods.' },
    ],
  },
];

export const SYSDESIGN_TOPICS: ConceptTopic[] = [
  {
    name: 'Core Building Blocks',
    items: [
      { name: 'Vertical vs Horizontal Scaling', explanation: 'Vertical scaling means making a single machine more powerful (more CPU, RAM). It\'s simple but has a hard ceiling and a single point of failure. Horizontal scaling means adding more machines and distributing load across them — it scales further and adds redundancy, but requires the system to be designed for distributed operation (stateless services, shared or partitioned data).' },
      { name: 'Load Balancing Strategies', explanation: 'Round robin distributes requests evenly regardless of server load. Least connections routes to whichever server currently has the fewest active requests, adapting better to uneven request costs. Consistent hashing routes the same kind of request to the same server consistently, which matters when a server holds request-specific cached state.' },
      { name: 'Caching Strategies', explanation: 'Cache-aside: the application checks the cache first, and on a miss, reads from the database and populates the cache itself. Write-through: every write goes to the cache and the database together, keeping them always in sync at the cost of write latency. Write-back: writes go to the cache first and are flushed to the database later, which is fast but risks data loss if the cache fails before flushing.' },
      { name: 'Database Sharding', explanation: 'Sharding splits a large dataset across multiple database instances, each responsible for a subset of the data (often by a key range or hash). This lets you scale storage and write throughput beyond what one machine can handle, but cross-shard queries and transactions become significantly harder to implement correctly.' },
      { name: 'Consistent Hashing', explanation: 'Consistent hashing maps both servers and data onto the same conceptual ring using a hash function, so each piece of data is owned by the nearest server clockwise on the ring. When a server is added or removed, only the data between it and its neighbor needs to move, instead of reshuffling everything — which is what makes it far more resilient to scaling changes than simple modulo-based hashing.' },
      { name: 'Message Queues', explanation: 'A message queue (like Kafka or RabbitMQ) decouples producers of work from consumers of that work — the producer drops a message on the queue and moves on, and consumers process messages independently at their own pace. This smooths out traffic spikes, lets services fail and recover without losing work, and lets you scale producers and consumers separately.' },
      { name: 'Rate Limiting Algorithms', explanation: 'Token bucket allows bursts up to a bucket\'s capacity while refilling tokens at a steady rate, which is common for balancing burstiness with an average rate limit. Sliding window log tracks exact request timestamps in a rolling window, giving precise limiting at the cost of more memory. Fixed window is simplest (count requests per fixed time block) but allows bursts right at window boundaries.' },
      { name: 'CAP Theorem Trade-offs', explanation: 'When a network partition happens, a distributed system must choose between staying consistent (rejecting some requests to avoid serving stale data) or staying available (serving requests even if the data might be slightly stale). Most real systems pick a point along that spectrum per use case rather than treating it as an absolute binary choice.' },
    ],
  },
  {
    name: 'Common Case Studies',
    items: [
      { name: 'Design a URL Shortener', explanation: 'Core idea: generate a short unique key (via a counter, hash, or random string with a collision check) for each long URL, store the mapping in a fast key-value store, and redirect on lookup. Worth discussing: how to handle key collisions, whether to support custom aliases, and how to scale reads (which vastly outnumber writes) with caching.' },
      { name: 'Design a Twitter-like Feed', explanation: 'Core idea: either compute each user\'s feed at write time (fan-out on write — push new posts to every follower\'s feed immediately, fast reads but expensive for users with huge followings) or at read time (fan-out on read — assemble the feed when requested, cheaper to write but slower to read). Most real systems use a hybrid: push for typical users, pull for celebrity accounts with huge follower counts.' },
      { name: 'Design a Chat Application', explanation: 'Core idea: persistent WebSocket connections for real-time delivery, a message queue or pub/sub layer to route messages between users (especially across multiple server instances), and a database for message history. Worth discussing: how to handle offline delivery, read receipts, and group chats at scale.' },
      { name: 'Design an E-commerce Cart & Checkout', explanation: 'Core idea: the cart itself can live in a fast key-value store keyed by user/session, while checkout needs strong transactional guarantees — inventory decrement, payment, and order creation should either all succeed or all roll back. Worth discussing: how to prevent overselling limited stock under concurrent checkouts, and how to handle payment failures gracefully.' },
      { name: 'Design a Rate Limiter', explanation: 'Core idea: pick an algorithm (token bucket is common), and decide where state lives — in-memory per server is fast but inconsistent across a fleet, so a shared store like Redis is typically used to enforce limits consistently across all servers handling a given user\'s requests.' },
      { name: 'Design a Notification System', explanation: 'Core idea: a queue-based pipeline where an event triggers a notification job, which is routed to the right delivery channel (push, email, SMS), with retries for failed deliveries and rate limiting per user to avoid overwhelming them. Worth discussing: how to deduplicate notifications and respect user preferences per channel.' },
      { name: 'Design a Video Streaming Service', explanation: 'Core idea: videos are transcoded into multiple resolutions/bitrates ahead of time, split into small chunks, and served through a CDN so users stream from a nearby edge server with adaptive bitrate switching based on their connection speed. Worth discussing: how upload/transcoding pipelines scale, and how metadata (views, recommendations) is served separately from the actual video bytes.' },
      { name: 'Design an API Gateway', explanation: 'Core idea: a single entry point in front of multiple backend services that handles cross-cutting concerns — authentication, rate limiting, request routing, and sometimes response aggregation — so individual services don\'t each need to reimplement them. Worth discussing: how it avoids becoming a single point of failure or a bottleneck itself.' },
    ],
  },
];

export const WEB_TOPICS: ConceptTopic[] = [
  {
    name: 'JavaScript Core',
    items: [
      { name: 'Closures', explanation: 'A closure is a function that remembers the variables from the scope it was created in, even after that outer scope has finished executing. This is how you get private state in JavaScript without classes — an inner function can keep referencing and modifying a variable that\'s otherwise inaccessible from outside.' },
      { name: 'Event Loop & Call Stack', explanation: 'JavaScript runs on a single thread with a call stack for currently executing code. Asynchronous work (timers, network calls) is handed off to the browser/runtime, and its callback is queued once ready. The event loop continuously checks: is the call stack empty? If so, take the next queued callback and push it onto the stack — this is why a `setTimeout(fn, 0)` still runs after all currently synchronous code finishes.' },
      { name: 'Promises vs Async/Await', explanation: 'A Promise represents a value that will be available later (or an error), with `.then()`/`.catch()` to react to it. Async/await is syntax sugar over Promises that lets you write asynchronous code that reads like synchronous code — `await` pauses the function until the Promise resolves, without blocking the rest of the program.' },
      { name: 'Hoisting', explanation: 'Variable and function declarations are conceptually moved to the top of their scope before code executes. `var` declarations are hoisted and initialized as undefined, `let`/`const` are hoisted but stay in an inaccessible "temporal dead zone" until their actual line runs, and function declarations (not expressions) are hoisted along with their full body.' },
      { name: "'this' keyword behavior", explanation: 'The value of `this` depends on how a function is called, not where it\'s defined. Called as a method (`obj.fn()`), `this` is the object. Called standalone, `this` is undefined (strict mode) or the global object. Arrow functions don\'t have their own `this` at all — they inherit it from the enclosing scope where they were defined, which is why they\'re often used to avoid `this` confusion inside callbacks.' },
      { name: 'Prototypal Inheritance', explanation: 'Every JavaScript object has an internal link to another object (its prototype), and when a property isn\'t found on the object itself, the lookup continues up the prototype chain. This is different from classical inheritance — objects inherit directly from other objects, rather than from a class blueprint, even though `class` syntax is mostly sugar over this same mechanism.' },
      { name: 'Debounce vs Throttle', explanation: 'Debounce delays running a function until a certain amount of time has passed since the last time it was called — useful for something like a search-as-you-type box, where you only want to fire once the user pauses. Throttle ensures a function runs at most once per fixed interval, no matter how often it\'s triggered — useful for something like a scroll handler that shouldn\'t fire on every single pixel of scroll.' },
      { name: '== vs ===', explanation: '`===` compares both value and type with no conversion. `==` performs type coercion before comparing, which can produce surprising results (like `"" == 0` being true). The near-universal advice is to always use `===` and only reach for `==` in the rare case you deliberately want the coercion.' },
    ],
  },
  {
    name: 'React',
    items: [
      { name: 'Virtual DOM & Reconciliation', explanation: 'React keeps an in-memory representation of the UI (the virtual DOM) and, on a state change, computes a new virtual DOM tree, then diffs it against the previous one to find the minimal set of real DOM changes needed — this "reconciliation" step is what makes updates fast, since touching the real DOM directly is comparatively expensive.' },
      { name: 'useState vs useEffect', explanation: '`useState` gives a component local state that persists across re-renders and triggers a re-render when updated. `useEffect` runs side effects (data fetching, subscriptions, manual DOM work) after render, and can clean up after itself when the component unmounts or before the effect re-runs — it\'s the hook-based replacement for lifecycle methods like componentDidMount/componentDidUpdate/componentWillUnmount.' },
      { name: 'Component Lifecycle (class & hooks)', explanation: 'Class components have named lifecycle methods: `componentDidMount` (after first render), `componentDidUpdate` (after subsequent renders), `componentWillUnmount` (before removal). Function components achieve the same behavior with `useEffect`, where the dependency array controls when it re-runs, and the returned cleanup function handles the unmount case.' },
      { name: 'Controlled vs Uncontrolled Components', explanation: 'A controlled input has its value driven entirely by React state — you read the value from state and update it via an onChange handler. An uncontrolled input manages its own internal state in the DOM, and you read its value on demand (e.g. via a ref) rather than syncing every keystroke through React.' },
      { name: 'Props vs State', explanation: 'Props are read-only data passed down from a parent component, and a component can\'t modify its own props. State is data owned and managed internally by a component, which it can update itself, triggering a re-render. Props flow down; state changes are local unless explicitly lifted up or passed down further.' },
      { name: 'Why Keys Matter in Lists', explanation: 'Keys tell React which items in a list correspond to which items after a re-render, so it can correctly reuse, reorder, or remove DOM elements instead of tearing everything down and rebuilding it. Using an unstable key (like an array index for a reorderable list) can cause React to mismatch items to the wrong DOM node, leading to bugs with component state or focus.' },
      { name: 'Context API', explanation: 'Context lets you pass data down through a component tree without manually threading props through every intermediate level ("prop drilling"). A Provider makes a value available, and any descendant component can read it via `useContext` — useful for things like theme, auth state, or locale that many components need access to.' },
      { name: 'Writing Custom Hooks', explanation: 'A custom hook is just a regular function whose name starts with `use` that calls other hooks internally, letting you extract and reuse stateful logic across components — for example, a `useFetch(url)` hook that handles loading/error/data state, so multiple components can fetch data without duplicating that logic.' },
    ],
  },
  {
    name: 'Node.js & APIs',
    items: [
      { name: 'REST API Design Principles', explanation: 'REST models a system as resources (nouns), accessed via standard HTTP verbs (GET to read, POST to create, PUT/PATCH to update, DELETE to remove), with URLs identifying resources rather than actions (`/users/5` rather than `/getUser?id=5`). Being stateless — each request carries everything needed to process it, with no server-side session — is a core REST constraint that makes horizontal scaling easier.' },
      { name: 'Middleware in Express', explanation: 'Middleware functions sit in the request-handling pipeline, each able to inspect or modify the request/response, then either pass control to the next middleware (`next()`) or end the response. This is how cross-cutting concerns like logging, authentication, and error handling get applied without duplicating that logic inside every individual route handler.' },
      { name: 'Authentication — JWT vs Sessions', explanation: 'Session-based auth stores session data server-side (often in a database or cache) and gives the client just an opaque session ID cookie — this is easy to revoke but requires shared session storage across server instances. JWT-based auth encodes the user\'s claims directly into a signed token the client holds, so any server can verify it without a shared store, but revoking a single JWT before it expires is much harder since the server isn\'t tracking it.' },
      { name: 'CORS', explanation: 'Cross-Origin Resource Sharing is a browser security mechanism that blocks a webpage from making requests to a different origin (domain/port/protocol) than it was loaded from, unless the target server explicitly allows it via response headers. It\'s a client-side (browser) restriction — a server can still be reached fine by tools like curl, since CORS is enforced by the browser, not the server.' },
      { name: 'Node.js Event Loop', explanation: 'Node runs JavaScript on a single thread but delegates I/O operations (file reads, network calls) to the underlying system (via libuv), so the main thread isn\'t blocked waiting for them — when an I/O operation completes, its callback is queued to run on the main thread once it\'s free. This is what lets Node handle many concurrent connections efficiently despite being single-threaded for JS execution.' },
      { name: 'Preventing SQL Injection', explanation: 'SQL injection happens when untrusted user input is directly concatenated into a SQL query string, letting an attacker inject their own SQL logic. The fix is parameterized queries (or prepared statements), where user input is passed as a separate bound parameter rather than being concatenated into the query text, so the database engine never interprets it as SQL syntax.' },
      { name: 'API Rate Limiting', explanation: 'Rate limiting caps how many requests a client can make in a given time window, protecting the API from abuse or accidental overload. It\'s typically implemented with an algorithm like token bucket or sliding window, tracked in a shared store (like Redis) if the API runs across multiple server instances, so limits are enforced consistently regardless of which instance handles a given request.' },
      { name: 'Microservices vs Monolith', explanation: 'A monolith is one deployable application containing all functionality, which is simpler to develop and deploy initially but can become unwieldy as it grows, and forces the whole thing to scale together. Microservices split functionality into independently deployable services communicating over the network, which allows independent scaling and deployment, at the cost of significantly more operational complexity — network calls, distributed data consistency, and service discovery all become real concerns.' },
    ],
  },
];
