// Generated by scripts/sync-version.mjs from package.json. Do not edit by hand —
// `npm run sync-version` (and every build) rewrites it.
export const APP_VERSION = '1.2.1';
export const APP_VERSION_CODE = 10201;
